batch_size: 16
iters: 10000

train_dataset:
  type: Dataset
  dataset_root: data/aeroscapes
  train_path: data/aeroscapes/ImageSets/train_paths.txt
  num_classes: 12
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/aeroscapes
  val_path: data/aeroscapes/ImageSets/validation_paths.txt
  num_classes: 12
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: OhemCrossEntropyLoss
  coef: [1]

model:
  type: DDRNet_23
  enable_auxiliary_loss: False
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/cityscapes/ddrnet23_cityscapes_1024x1024_120k/pretrain/model.pdparams