batch_size: 16
iters: 10000

train_dataset:
  type: Dataset
  dataset_root: data/aeroscapes
  train_path: data/aeroscapes/ImageSets/train_paths.txt
  num_classes: 12
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/aeroscapes
  val_path: data/aeroscapes/ImageSets/validation_paths.txt
  num_classes: 12
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 2.2618605764487565e-05

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.06062632735545464
  end_lr: 8.437349656728206e-05
  power: 0.9

loss:
  types:
  - type: OhemCrossEntropyLoss
    min_kept: 200000   # batch_size * 512* 512 // 16
  - type: OhemCrossEntropyLoss
    min_kept: 200000
  - type: OhemCrossEntropyLoss
    min_kept: 200000
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]