batch_size: 16
iters: 15000

train_dataset:
  type: Dataset
  dataset_root: data/VDD_1
  train_path: data/VDD_1/metadata/traindata.txt
  num_classes: 7
  mode: train
  transforms:
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/VDD_1
  val_path: data/VDD_1/metadata/valdata.txt
  num_classes: 7
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
  - type: OhemCrossEntropyLoss
    min_kept: 200000   # batch_size * 512* 512 // 16
  - type: OhemCrossEntropyLoss
    min_kept: 200000
  - type: OhemCrossEntropyLoss
    min_kept: 200000
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]